# Generated by Django 4.2.13 on 2024-07-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_vehicle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='name',
            field=models.CharField(default='Lamboquine', max_length=100, unique=True),
        ),
    ]
