# Generated by Django 4.2.13 on 2024-07-03 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_vehicle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='name',
        ),
    ]
