# Generated by Django 4.2.13 on 2024-07-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_vehicle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_name',
            field=models.CharField(default='Lamboquine', max_length=100, unique=True),
        ),
    ]
