# Generated by Django 4.2.13 on 2024-07-03 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_vehicle_vehicle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_name',
        ),
    ]
